---

- name: create a service user (default is ec2-user)
  user:
    name: '{{ service_user_name }}'
    password: '{{ service_user_password }}'
    create_home: true
    # groups: solr,tomcat
    #   - sudo # requires some tinkering to make work
    state: present

